### ISSUE TITLE
Peer Grading: set directory for compiled views

### ISSUE THREAD

**Issue by lsloan** [tl-its-umich-edu/docker-base-images#21]
By default, Laravel compiles view templates and stores them in `/var/www/html/storage/framework/views`.  However, in OpenShift, the filesystem is read-only.  In a conversation with @chrispittman, he suggested setting `VIEW_COMPILED_PATH=/tmp` in the environment should work.  Indeed it does!

**Comment by chrispittman** [comment]
FYI, you can also set it to a subdirectory of `/tmp` if you want - `/tmp/laravelviews` or somesuch - if you want to keep these constrained a directory of their own for whatever reason.  Laravel will create the subdir if it doesn't already exist.
