### ISSUE TITLE
update to newest tagged image of UT Austin qualtrics-lti tool

### ISSUE THREAD

**Issue by zqian** [tl-its-umich-edu/docker-base-images#5]
We currently pull the [qualtrics-lti:20220606](https://github.com/longhornopen/qualtrics-lti/pkgs/container/qualtrics-lti/24378631?tag=20220606) image inside qualtrics-lti/Dockerfile.umich file.

Need to update to the current [qualtrics-lti:20221020](https://github.com/longhornopen/qualtrics-lti/pkgs/container/qualtrics-lti/46649328?tag=20221020) image for added LTI 1.3 support.

**Comment by jonespm** [comment]
This was updated in #9
